#!/bin/sh

DAEMON="/usr/local/bin/schoolbell.py"
PIDFILE="/var/run/schoolbell.pid"

start() {
    printf "Starting school bell: "
    start-stop-daemon -S -b -m -p "$PIDFILE" --exec /usr/bin/python3 -- "$DAEMON"
    echo "ok"
}

stop() {
    printf "Stopping school bell: "
    start-stop-daemon -K -p "$PIDFILE"
    echo "ok"
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
